### ISSUE TITLE
Traefik port forward

### ISSUE THREAD

**Issue by randinfo** [tellform/tellform#176]
Hello,

I'm trying to use tellform with traefik but i got some issues.
Here is my conf:

```
version: '2'

services:
  tellform:
    image: tellform/production:no_subdomains
    ports:
      - 3000
      - 80
    links:
      - redis:redis-db
      - mongo:db
    environment:
      - BASE_URL=tellform.mydomain.com
      - DB_1_PORT_27017_TCP_ADDR=mongo
      - REDIS_DB_PORT_6379_TCP_ADDR=redis
    networks:
      - traefik
      - tellform
    labels:
      - "traefik.frontend.rule=Host:tellform.mydomain.com"
      - "traefik.port=3000"
      - "traefik.enable=true"
      - "traefik.backend=tellform"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=traefik"
  redis:
    image: redis:alpine
    ports:
      - 6379
    labels:
      - "traefik.enable=false"
    networks:
      - tellform
  mongo:
    image: mongo:latest
    ports:
      - 27017
    labels:
      - "traefik.enable=false"
    networks:
      - tellform
networks:
  tellform:
    driver: bridge
  traefik:
    external:
      name: traefik

```

With this configuration i'm getting this in the console log :
```
[4mRunning "concurrent:default" (concurrent) task[24m
    [4mRunning "watch" task[24m
    Waiting...
    [4mRunning "nodemon:dev" (nodemon) task[24m
    [33m[nodemon] 1.11.0[39m
    [33m[nodemon] to restart at any time, enter `rs`[39m
    [33m[nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js[39m
    [32m[nodemon] starting `node --debug server.js`[39m
    --
    Environment:			production
    Port:				3000
    Database:			mongodb://mongo/mean
    --
    Successfully created Admin Account

```

So it's supossed to be working but it's not i got an "ERR_CONNECTION_CLOSED" error

Have anyone already tried it with traefik ?

Thanks in advance.
